version: "3.8"

services:
  api:
    build: .
    command: tail -f /dev/null
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: mongo
    restart: always
    volumes:
      - db_volume:/data/db
  
volumes:
  db_volume: